[project]
name = "aisafetyconnect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.4.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
]
